### ISSUE TITLE
大佬，你好，咱们库接入银联出现了展示错误

### ISSUE THREAD

**Issue by WangYiOS** [xmy1231/flutter_union_pay#1]
`
-canOpenURL: failed for URL: "uppaywallet://" - error: "未能完成操作。（OSStatus错误-10814。）"
-canOpenURL: failed for URL: "uppayx1://" - error: "未能完成操作。（OSStatus错误-10814。）"
`

传的参数照例子写的，银联支付也调起来了，但爆了以上错误，

![WechatIMG20](https://user-images.githubusercontent.com/17872114/176585443-013b359c-c375-4d86-8883-ffd3a0477cc9.jpeg)

**Comment by WangYiOS** [comment]
大佬，我问了朋友，大致是说您的库，版本低了

求你更新，

flutter世界里的银联支付，可就您一个啊

你不能倒啊！！！！！！

**Comment by WangYiOS** [comment]
大佬，我错了。

咱的包没问题，是debug（PaymentEnv.DEVELOPMENT）下银联界面显示错误，但relase（PaymentEnv.PRODUCT）银联界面就可正常支付。

很棒，能正常使用。关了我的问题吧


![Snip20220630_6](https://user-images.githubusercontent.com/17872114/176601535-c3c58068-32ca-4115-9564-48477ac9fcd0.png)

![WechatIMG20](https://user-images.githubusercontent.com/17872114/176601675-aa9cb079-df36-4054-b7a3-69baa2c49881.jpeg)

![WechatIMG21](https://user-images.githubusercontent.com/17872114/176601747-3666f034-e920-41bd-ac7e-48f450f6d2e3.jpeg)

**Comment by xmy1231** [comment]
好的
