### ISSUE TITLE
大佬，你好，提个需求，flutter版本最新SDK是3.7.10，咱们的union_pay暂不支持！

### ISSUE THREAD

**Issue by WangYiOS** [xmy1231/flutter_union_pay#2]
如题所示：
大佬，你好，提个需求，flutter版本最新SDK是3.7.10，咱们的union_pay暂不支持！
是否能更新下银联版本，跟上最新的flutter SDK，望回复！
==============
这周把flutter从2.x版本升级到了现在最新的3.7.10，发现咱们的union_pay无法适配flutterSDK，
在这里和大佬讲下。

**Comment by WangYiOS** [comment]
下面是报的错误：
`FAILURE: Build failed with an exception.

* Where:
Build file '/Users/yingpan/.pub-cache/hosted/pub.flutter-io.cn/union_pay-1.0.1/android/build.gradle' line: 40

* What went wrong:
A problem occurred evaluating project ':union_pay'.
> Could not find method useProguard() for arguments [false] on BuildType$AgpDecorated_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType$AgpDecorated.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by xmy1231** [comment]
你好，看你的报错应该是混淆的问题，试着下面的方法解决：
useProguard true <----- 删除这行
或者 
minifyEnabled false 代替 useProguard false
 
 我这边有空也更新一下银联的版本
