### ISSUE TITLE
iOS 这里应该 return NO

### ISSUE THREAD

**Issue by lionnner** [xmy1231/flutter_union_pay#3]
https://github.com/xmy1231/flutter_union_pay/blob/e3091cdc5e0bcc578e6ec4b2500b40f4eab72b4c/ios/Classes/FlutterUnionPayPlugin.m#L80

**Comment by xmy1231** [comment]
你好，官方的接入指南参考如下：
![image](https://github.com/xmy1231/flutter_union_pay/assets/10206252/e1f1a4bc-1c04-4bbb-ae1d-9b4eefb90317)

**Comment by lionnner** [comment]
> 你好，官方的接入指南参考如下： ![image](https://private-user-images.githubusercontent.com/10206252/291811518-e1f1a4bc-1c04-4bbb-ae1d-9b4eefb90317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTgxODMsIm5iZiI6MTcwMzA1Nzg4MywicGF0aCI6Ii8xMDIwNjI1Mi8yOTE4MTE1MTgtZTFmMWE0YmMtMWMwNC00YmJiLWFlMWQtOWI0ZWVmYjkwMzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA3MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZGIxZDg5OGZiOTQyMWYwMmVmYzBiODg0ZjkzMGIxM2E3NTkxZjhlNTY3NmE0ZGVmNWZjMTkxZTkxOTJmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c_6szusOKC-FzRbe671SW3r8aZKBfhlWI6MkGQeMjBw)

如果同时用到了微信分享fluwx，这个插件先响应，这里返回YES， 那么fluwx的回调就不会走了。
https://github.com/OpenFlutter/fluwx/blob/1218f66e8e2b2470447c19db48787cccdf192927/ios/Classes/FluwxPlugin.m#L416

**Comment by xmy1231** [comment]
能具体说一下你的使用场景吗？

**Comment by lionnner** [comment]
1. - (BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options 这个方法一旦返回YES，那么其他插件的这个方法就不会响应了。

2. 如果APP 使用了多个插件依赖此方法做回调(分享类 fluwx ，QQ/支付宝登录类)，GeneratedPluginRegistrant.m 里会自动注册使用的插件，注册的顺序是按照字母排序的。

在以上条件下， 比如使用了一个C插件且该插件的注册顺序在UniLinksPlugin之后，系统会优先回调UniLinksPlugin 里的 - (BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options方法，UniLinksPlugin一旦返回YES，那C插件的这个方法就不响应了。


题外话：- (void)handlePaymentResult:(NSURL*)url completeBlock:(UPPaymentResultBlock)completionBlock
 这个库的方法写的不标准， 应该返回一个BOOL，使用的时候直接 return [[UPPaymentControl defaultControl] handlePaymentResult:(NSURL*)url completeBlock:(UPPaymentResultBlock)completionBlock] 才是正解，为了不影响其他插件的使用，只能无脑返回NO了

**Comment by xmy1231** [comment]
你好， 感谢你的反馈，由于本人Xcode问题，我这边抽空改一下的。
